In [1]:
!wget https://raw.githubusercontent.com/McahitKutsal/turk-gpt/main/romeovejulyet.txt

--2024-04-13 22:24:53--  https://raw.githubusercontent.com/McahitKutsal/turk-gpt/main/romeovejulyet.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 449622 (439K) [text/plain]
Saving to: ‘romeovejulyet.txt’

romeovejulyet.txt   100%[===================>] 439.08K  --.-KB/s    in 0.004s  

2024-04-13 22:24:54 (109 MB/s) - ‘romeovejulyet.txt’ saved [449622/449622]



In [2]:
with open('romeovejulyet.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [3]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  400810


In [4]:
print(text[:1000])

İlk Vatandaş:
Daha fazla ilerlemeden önce konuşmamı dinleyin.

Tüm:
Konuş, konuş.

İlk Vatandaş:
Hepiniz açlıktan ölmek yerine ölmeye mi karar verdiniz?

Tüm:
Çözüldü. çözüldü.

İlk Vatandaş:
Öncelikle Caius Marcius'un halkın baş düşmanı olduğunu biliyorsunuz.

Tüm:
Bilmiyoruz, bilmiyoruz.

İlk Vatandaş:
Onu öldürelim ve kendi fiyatımıza mısır alalım.
Bir hüküm değil mi?

Tüm:
Artık konuşmak yok; bırakın yapılsın: uzakta, uzakta!

İkinci Vatandaş:
Tek kelimeyle iyi vatandaşlar.

İlk Vatandaş:
Biz fakir vatandaşlar olarak görülüyoruz, soylular ise iyi.
Hangi otoritenin fazlalığı bizi rahatlatır: eğer onlar
bize fazlalıktan başka bir şey vermezdi, oysa
sağlıklı, bizi insanca rahatlattıklarını tahmin edebiliriz;
ama bizim çok sevgili olduğumuzu düşünüyorlar: zayıflık
bizi üzen, sefaletimizin nesnesi olan,
bolluklarını özelleştirmek için envanter; bizim
Çekilmek onlar için kazançtır Bunun intikamını onunla alalım
mızraklarımız, tırmık olmadan önce: çünkü tanrılar biliyor ki ben
Bunu intika

In [5]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !"',-.:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzÇÖÜâçöûüĞğİıŞş
77


In [6]:
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

print(encode("hii there"))
print(decode(encode("hii there")))

[44, 45, 45, 1, 56, 44, 41, 54, 41]
hii there


In [7]:
import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000])

torch.Size([400810]) torch.int64
tensor([73, 48, 47,  1, 32, 37, 56, 37, 50, 40, 37, 76,  8,  0, 14, 37, 44, 37,
         1, 42, 37, 62, 48, 37,  1, 45, 48, 41, 54, 48, 41, 49, 41, 40, 41, 50,
         1, 68, 50, 39, 41,  1, 47, 51, 50, 57, 76, 49, 37, 49, 74,  1, 40, 45,
        50, 48, 41, 61, 45, 50,  7,  0,  0, 30, 70, 49,  8,  0, 21, 51, 50, 57,
        76,  5,  1, 47, 51, 50, 57, 76,  7,  0,  0, 73, 48, 47,  1, 32, 37, 56,
        37, 50, 40, 37, 76,  8,  0, 18, 41, 52, 45, 50, 45, 62,  1, 37, 67, 48,
        74, 47, 56, 37, 50,  1, 68, 48, 49, 41, 47,  1, 61, 41, 54, 45, 50, 41,
         1, 68, 48, 49, 41, 61, 41,  1, 49, 45,  1, 47, 37, 54, 37, 54,  1, 58,
        41, 54, 40, 45, 50, 45, 62, 10,  0,  0, 30, 70, 49,  8,  0, 63, 68, 62,
        70, 48, 40, 70,  7,  1, 67, 68, 62, 70, 48, 40, 70,  7,  0,  0, 73, 48,
        47,  1, 32, 37, 56, 37, 50, 40, 37, 76,  8,  0, 64, 50, 39, 41, 48, 45,
        47, 48, 41,  1, 13, 37, 45, 57, 55,  1, 23, 37, 54, 39, 45, 57, 55,  4,
       

In [8]:
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

In [9]:
block_size = 8
train_data[:block_size+1]

tensor([73, 48, 47,  1, 32, 37, 56, 37, 50])

In [10]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([73]) the target: 48
when input is tensor([73, 48]) the target: 47
when input is tensor([73, 48, 47]) the target: 1
when input is tensor([73, 48, 47,  1]) the target: 32
when input is tensor([73, 48, 47,  1, 32]) the target: 37
when input is tensor([73, 48, 47,  1, 32, 37]) the target: 56
when input is tensor([73, 48, 47,  1, 32, 37, 56]) the target: 37
when input is tensor([73, 48, 47,  1, 32, 37, 56, 37]) the target: 50


In [11]:
torch.manual_seed(1337)
batch_size = 4
block_size = 8

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[73, 63, 15,  1, 15, 22, 73, 36],
        [54,  1, 47, 74, 55, 74, 49, 48],
        [41, 48, 37, 49, 55, 74, 62,  1],
        [ 1, 43, 41, 67, 41, 54, 55, 41]])
targets:
torch.Size([4, 8])
tensor([[63, 15,  1, 15, 22, 73, 36, 11],
        [ 1, 47, 74, 55, 74, 49, 48, 37],
        [48, 37, 49, 55, 74, 62,  1, 38],
        [43, 41, 67, 41, 54, 55, 41, 50]])
----
when input is [73] the target: 63
when input is [73, 63] the target: 15
when input is [73, 63, 15] the target: 1
when input is [73, 63, 15, 1] the target: 15
when input is [73, 63, 15, 1, 15] the target: 22
when input is [73, 63, 15, 1, 15, 22] the target: 73
when input is [73, 63, 15, 1, 15, 22, 73] the target: 36
when input is [73, 63, 15, 1, 15, 22, 73, 36] the target: 11
when input is [54] the target: 1
when input is [54, 1] the target: 47
when input is [54, 1, 47] the target: 74
when input is [54, 1, 47, 74] the target: 55
when input is [54, 1, 47, 74, 55] the target: 74
when input is [54, 

In [12]:
print(xb)

tensor([[73, 63, 15,  1, 15, 22, 73, 36],
        [54,  1, 47, 74, 55, 74, 49, 48],
        [41, 48, 37, 49, 55, 74, 62,  1],
        [ 1, 43, 41, 67, 41, 54, 55, 41]])


In [13]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            logits, loss = self(idx)
            logits = logits[:, -1, :] # becomes (B, C)
            probs = F.softmax(logits, dim=-1) # (B, C)
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 77])
tensor(5.0522, grad_fn=<NllLossBackward0>)

qGümW 
ESGğnJ;IUFâöJIiqCir"Ut!l!ŞLW'tç.tV!SdÜ'tQ-üEüI
zDÜpkJHa--Y
üFdYY'wvB ÜPVÖnpşJpzRvsOIöAqSePö Ü


In [14]:
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [15]:
batch_size = 32
for steps in range(100):

    xb, yb = get_batch('train')

    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


4.6897172927856445


In [16]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


vZİĞjdğWÖtFcçMNOŞİeLz "Ğ?â."WQAfsvM:m:PPçfab?ÖnsÜJ;IiUZYğSREÖüwOİDc.dûû!"JqnfÖötçf
ğzjCLa-öÜae".BzzEİŞ-fLdT g,ZQA,w"ljqgPTR:Uqş;bHûÇKMPöZcXıĞ?ÖhdogDD'AÇcjdÇoWIöOxÖW.R!iFZcp
ÇÖqrisOıyüY?dpZI!VivbrToÜpÖŞ'BĞrPKu!d-jdLkJÜlvOİöÜEVG'EÖHVJ öQÇNYVdTrTfEaMNwİNûH;T,siıO
ğZYpMhR
q?z;XvkN?pkİoszVhj
xSG:mhHV"lıuÇkWoWĞıuJCtRmZWx?
qdgfrOPk"-zşsJQtntvqAPRşMĞ;vrÖWK şr-oİysQFmZ;eszüXbg 
lMoĞJÖsDkOpHPf MŞMİolğiâjQÇıÇXPŞnYDmûq?,C?-os:C?ÜGx?ĞÖhSçfnsOhfyöNâ,wÇnneO.KmgOE-OŞÜBibDZtAUxUFRRQ"fLzrQcjPkPQİdÇiç;,-!ıs.hinsyŞ


## The mathematical trick in self-attention

In [17]:
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [18]:

torch.manual_seed(1337)
B,T,C = 4,8,2
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [19]:
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1]
        xbow[b,t] = torch.mean(xprev, 0)


In [20]:
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x
torch.allclose(xbow, xbow2)

False

In [21]:
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)


False

In [22]:
torch.manual_seed(1337)
B,T,C = 4,8,32
x = torch.randn(B,T,C)

head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)
q = query(x)
wei =  q @ k.transpose(-2, -1)

tril = torch.tril(torch.ones(T, T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v

out.shape

torch.Size([4, 8, 16])

In [24]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [25]:
k.var()

tensor(1.0449)

In [26]:
q.var()

tensor(1.0700)

In [27]:
wei.var()

tensor(1.0918)

In [28]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [29]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1)

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [30]:
class LayerNorm1d:
  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100)
x = module(x)
x.shape

torch.Size([32, 100])

In [31]:
x[:,0].mean(), x[:,0].std()

(tensor(0.1469), tensor(0.8803))

In [32]:
x[0,:].mean(), x[0,:].std()

(tensor(-9.5367e-09), tensor(1.0000))

### Full finished code, for reference

You may want to refer directly to the git repo instead though.

In [34]:
from google.colab import files
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 64 # how many independent sequences will we process in parallel?
block_size = 256
max_iters = 20000
eval_interval = 1000
learning_rate = 1e-4
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 384
n_head = 8
n_layer = 8
dropout = 0.2
# ------------

torch.manual_seed(1337)

with open('romeovejulyet.txt', 'r', encoding='utf-8') as f:
    text = f.read()

chars = sorted(list(set(text)))
vocab_size = len(chars)
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        wei = q @ k.transpose(-2,-1) * C**-0.5
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))
        wei = F.softmax(wei, dim=-1)
        wei = self.dropout(wei)
        v = self.value(x)
        out = wei @ v
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        tok_emb = self.token_embedding_table(idx)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device))
        x = tok_emb + pos_emb
        x = self.blocks(x)
        x = self.ln_f(x)
        logits = self.lm_head(x)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            idx_cond = idx[:, -block_size:]
            logits, loss = self(idx_cond)
            logits = logits[:, -1, :] # becomes (B, C)
            probs = F.softmax(logits, dim=-1) # (B, C)
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)
import time
start_time = time.time()
for iter in range(max_iters):
    if iter % eval_interval == 0 or iter == max_iters - 1:
        end_time = time.time()  # end time
        elapsed_time = end_time - start_time
        start_time = end_time
        print(f"elapsed time: {elapsed_time}")
        losses = estimate_loss()
        torch.save(m.state_dict(), f"/content/drive/My Drive/bigram_model_turk_step {iter}.pth")
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    xb, yb = get_batch('train')

    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))

14.344781 M parameters
elapsed time: 0.00019550323486328125
step 0: train loss 4.5644, val loss 4.5590
elapsed time: 754.0278787612915
step 1000: train loss 1.9018, val loss 2.0831
elapsed time: 758.3439583778381
step 2000: train loss 1.4939, val loss 1.7238
elapsed time: 758.2143104076385
step 3000: train loss 1.3092, val loss 1.5938
elapsed time: 758.1591382026672
step 4000: train loss 1.1841, val loss 1.5325
elapsed time: 758.1946711540222
step 5000: train loss 1.0689, val loss 1.5200
elapsed time: 757.8809194564819
step 6000: train loss 0.9553, val loss 1.5409
elapsed time: 758.010490655899
step 7000: train loss 0.8383, val loss 1.5813


In [ ]:
# from google.colab import files
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
# model2 = BigramLanguageModel()


# model2.load_state_dict(torch.load('/content/drive/My Drive/bigram_model_step 12000.pth', map_location=device))

# # Move the model to the appropriate device
# m2 = model2.to(device)

In [ ]:
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(context)

In [ ]:
# generate from the model
print(decode(m.generate(context, max_new_tokens=1000)[0].tolist()))